# Generated by Django 4.2.3 on 2024-01-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('reason_disability', models.TextField(blank=True, default='', editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='V2ray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_time', models.PositiveIntegerField()),
                ('volume', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('reason_disability', models.TextField(blank=True, default='', editable=False)),
                ('referral_bonus', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('operator', models.ManyToManyField(related_name='v2ray_operator', to='v2ray.operator')),
            ],
        ),
    ]
